### ISSUE TITLE
player related end points not working, return server error

### ISSUE THREAD

**Issue by Peppershaker** [bradleyfay/py-Goldsberry#17]
please confirm that player related API calls are still allowed by the server. I'm getting 403 Client Error: Forbidden for url

playerdashboardbygeneralsplits

**Comment by danielmcintosh1** [comment]
@Peppershaker This data appears to only be available in aggregate terms currently via headerless calls and we are working on a fix. 
I've tried http://stats.nba.com/player/#!/203919/stats/advanced/ and the webbrowser makes a call to http://stats.nba.com/stats/playerdashboardbygeneralsplits?DateFrom=&DateTo=&GameSegment=&LastNGames=0&LeagueID=00&Location=&MeasureType=Advanced&Month=0&OpponentTeamID=0&Outcome=&PORound=0&PaceAdjust=N&PerMode=PerGame&Period=0&PlayerID=203919&PlusMinus=N&Rank=N&Season=2015-16&SeasonSegment=&SeasonType=Regular+Season&ShotClockRange=&VsConference=&VsDivision= in order to render the information.
However, If I take that call and try to make it on it's own, I get a "referral denied error" and am told I do not have permission to access the server. This is different than the other calls in the package that return JSON data sources.

**Comment by Peppershaker** [comment]
thanks dude! also apparently the log level information are gone now. do you have any old files just so i can have a look what i missed out on? I just started looking at this script. Thanks again!

**Comment by danielmcintosh1** [comment]
@Peppershaker  Here is a small sample of shot data that used to be available. [Sample Data.xlsx](https://github.com/bradleyfay/py-Goldsberry/files/112965/Sample.Data.xlsx)

**Comment by Peppershaker** [comment]
thanks dude, but sad to see that go...

**Comment by bradleyfay** [comment]
should be fixed now outside of what the NBA blocked
